apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: dtest
spec:
  selector:
    matchLabels:
      app: dtest
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: dtest
    spec:
      containers:
      - name: dtest
        image: dgupton75/bulletinboard2:2.2
        ports:
        - containerPort: 8080

