apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  ports:
  - port: 3306
  selector:
    app: mysql
  clusterIP: None
apiVersion: v1
kind: Service
metadata:
  name: sql-s
  labels:
    name: sql-s
spec:
  type: NodePort
  ports:
    - port: 3306
      nodePort: 31000
      type: https
  selector:
    app: mysql

