apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb-config
data:
  initdb.sql: |
    create database DTEST1;
    use DTEST1;
    CREATE TABLE events (id INT AUTO_INCREMENT PRIMARY KEY, title TEXT, details TEXT, date DATE);
    INSERT INTO events (id,title, details, date) VALUES (1,'aab','bbc',NOW());
