apiVersion: v1
kind: Service
metadata:
  name: sql-s
  labels:
    name: sql-s
spec:
  type: NodePort
  ports:
    - port: 3306
      nodePort: 31000
      type: https
  selector:
    app: mysql

apiVersion: v1
kind: Service
metadata:
  #name: mysql
  name: $${sqlServiceName}
spec:
  ports:
  - port: 3306
